# Site settings
title: "Open Source && Free"
email: web@wearefree.ca
description: "Free Advertising's open source projects."
baseurl: ""
url: "http://wearefree.ca"

# Build settings
markdown: kramdown
permalink: pretty
